import { RarityValue } from "./FortniteCosmetics.type";

export const rarityEmojisTable: Record<RarityValue, string> = {
    "common": "⚪",
    "uncommon": "🟢",
    "rare": "🔵",
    "epic": "🟣",
    "legendary": "🟠",
    "marvel": "🔴",
    "starwars": "✨",
    backpack: "",
    banner: "",
    contrail: "",
    dark: "",
    dc: "",
    emoji: "",
    emote: "",
    frozen: "",
    gaminglegends: "",
    glider: "",
    icon: "",
    lava: "",
    loadingscreen: "",
    music: "",
    mythic: "",
    outfit: "",
    pet: "",
    petcarrier: "",
    pickaxe: "",
    shadow: "",
    slurp: "",
    spray: "",
    toy: "",
    wrap: ""
}